### ISSUE TITLE
Release tag(s)

### ISSUE THREAD

**Issue by notpeter** [ArchiveTeam/wget-lua#2]
Would it be possible to tag a release at some point?

Looks there have been a number of changes since this was forked from upstream and since [wget-1.14.lua.20160530-955376b](http://warriorhq.archiveteam.org/downloads/wget-lua/) (2016!) 

Similarly, is there a commit which corresponds to that tarball? I'm not seeing 955376b in this tree.

**Comment by chfoo** [comment]
That tarball came from https://github.com/alard/wget-lua/commit/955376b before this repository was made. I don't know which stable commits people used for projects previously, but I can try to see if automated tagging and builds can be made for the latest and future ones.

**Comment by marked** [comment]
Another tar ball is mentioned here https://launchpad.net/~archiveteam/+archive/ubuntu/wget-lua/+packages

**Comment by kpcyrd** [comment]
Tagging releases for this would allow me to upload it to archlinux, replacing the currently defunct [aur package](https://aur.archlinux.org/packages/wget-lua/).

**Comment by Fusl** [comment]
Let me know if this is sufficient for you: https://github.com/ArchiveTeam/wget-lua/releases/tag/v1.20.3 (Do note that the release refers to the `v1.20.3` tag which refers to the `v1.20.3-release` branch which is based on the `v1.20.3` branch but with commit https://github.com/ArchiveTeam/wget-lua/commit/30002883659ad2b21be002fb90854469ad99dbab setting `./.version` and `./.tarball-version` to the correct version.)

**Comment by notpeter** [comment]
Hi @Fusl! Thanks for taking a crack at this. Can you take a minute to explain what's going on with that release branch vs master? I was kinda surprised that branch seems to have a lot of code which is not in master, specifically https://github.com/ArchiveTeam/wget-lua/commit/7ea61485fa72c35a9868958468a71f326ec1251a includes +1000 lines (from upstream wget I assume?)

I don't fully understand the development workflow here, but ideally a release tag reference a commit on master if at all possible.  I think the need for explicit `.version` / `.tarball-version` files is because `build-aux/git-version.gen` is missing from this repo.  It's referenced both in the configure script and the makefile:

https://github.com/ArchiveTeam/wget-lua/blob/509af2ff96e2194cf1145dabafc30f36d7e24d61/Makefile.am#L48
https://github.com/ArchiveTeam/wget-lua/blob/509af2ff96e2194cf1145dabafc30f36d7e24d61/configure.ac#L34

If this comment is correct I think a signed tag may remove the need for adding those files onto the leaf branch.  But maybe @rockdaboot can shed more light on the intended process. https://github.com/ArchiveTeam/wget-lua/blob/509af2ff96e2194cf1145dabafc30f36d7e24d61/contrib/release#L3-L7

**Comment by rockdaboot** [comment]
A git tag (not even signed) should do it. The comment was mainly a reminder for myself - I don't have `.tarball-version` nor `build-aux/git-version-gen` lying around here (I build from git always).

Sorry for the incovenience, but this is from times before me becoming maintainer - and wget 1.x is in 'maintenance mode' (new stuff goes into wget2), so we won't change it.

Hope that helps a bit :man_shrugging:

**Comment by Fusl** [comment]
@notpeter The individual branches are up to date pulls from the upstream wget repository with the Lua patches manually applied tested. I'll look into undoing the patch for manually applying the version number and release a new tag soon with an `-at-lua` suffix (including the `-at-` part was proposed by an team member to make it clear that this is a special Archive Team build).

@rockdaboot Thanks a lot for the note.

**Comment by Arkiver2** [comment]
https://github.com/ArchiveTeam/wget-lua/releases/tag/v1.20.3-at.20200401.01 was just released.

**Comment by JustAnotherArchivist** [comment]
I added tags today for all past versions that I'm aware of. This includes all the tarballs on http://warriorhq.archiveteam.org/downloads/wget-lua/ (which also means I imported that entire branch as v1.14.lua) and all the v1.20.3-at versions.

See also the original ArchiveTeam/wget-lua repository which was renamed a while ago to make room for this one: https://github.com/ArchiveTeam/wget-lua-og

**Comment by notpeter** [comment]
Thank you @JustAnotherArchivist.  I very much appreciate the follow through. Have a wonderful day!
