### ISSUE TITLE
Payload digests containing NUL characters are truncated

### ISSUE THREAD

**Issue by ClosedPort22** [ArchiveTeam/wget-lua#25]
### Steps to reproduce
```sh
$ wget --warc-file=test https://desuarchive.org/foolfuuka/foolz/foolfuuka-theme-foolfuuka/assets-1.2.28/bootstrap.legacy.css
$ gzcat test.warc.gz | grep WARC-Payload-Digest
WARC-Payload-Digest: sha1:FQMDKAAAAAAAAAAAAAAAAAAAAAAAAAAA
```
The correct digest should be `FQMDKAH242AMMDOXGGQGEBZKYC2KMOER`.

### Environment
```text
$ wget --version
GNU Wget 1.21.3-at.20231215.01 built on freebsd13.3.

+cares +digest -gpgme +https +ipv6 +iri +large-file -metalink -nls
+ntlm +opie +psl +ssl/openssl

Wgetrc:
    /usr/local/etc/wgetrc (system)
Compile:
    cc -DHAVE_CONFIG_H -DSYSTEM_WGETRC="/usr/local/etc/wgetrc"
    -DLOCALEDIR="/usr/local/share/locale" -I. -I../lib -I../lib
    -D_THREAD_SAFE -I/usr/local/include -I/usr/include/luajit-2.1
    -I/usr/local/include -I/usr/local/include -I/usr/local/include/uuid
    -I/usr/local/include -I/usr/local/include -I/usr/local/include
    -DHAVE_LIBSSL -I/usr/local/include -I/usr/local/include -DNDEBUG -g
    -O2
Link:
    cc -I/usr/local/include -I/usr/local/include
    -I/usr/local/include/uuid -I/usr/local/include -I/usr/local/include
    -I/usr/local/include -DHAVE_LIBSSL -I/usr/local/include
    -I/usr/local/include -DNDEBUG -g -O2 -L/usr/local/lib -lcares
    -L/usr/local/lib -lpcre2-8 -L/usr/local/lib -luuid -L/usr/local/lib
    -lidn2 -L/usr/local/lib -lssl -lcrypto -L/usr/local/lib -lzstd -lz
    -L/usr/local/lib -lpsl -lm -ldl -lluajit-5.1 ../lib/libgnu.a
    /usr/local/lib/libiconv.so -Wl,-rpath -Wl,/usr/local/lib
    /usr/local/lib/libunistring.so -Wl,-rpath -Wl,/usr/local/lib
```

### Analysis

This is caused by the call to `strncpy` in `warc.c` at line 2085. Any digest containing `\0` will be terminated prematurely
https://github.com/ArchiveTeam/wget-lua/blob/c1fe6093eda544fc7a933f7646225bec1ff4bd8d/src/warc.c#L2062-L2085

### Solution

This could be fixed by simply replacing `strncpy` with `memcpy`. As someone who isn't very familiar with C, I'm not quite sure why copying is needed in the first place. I've removed this [in my fork of the project](https://github.com/ClosedPort22/wget-AT/commit/560a15850248543e162a47b57b6e8436c51cd0be) and it's working fine.

**Comment by nicolas17** [comment]
This strncpy was introduced in 4fda5f2cc5188a1db15ff5b0d535d56aafc5a4de. Copying at all is indeed unnecessary, but I can see how one would fail to notice that in the process of making the change. The real problem is using strncpy...

**Comment by Arkiver2** [comment]
This is now fixed with https://github.com/ArchiveTeam/wget-lua/commit/8adeb442e256ca8c737da19cc0224e1ca09ef266. Thank you very much for the report!

This problem reported here would cause incorrect payload digests to be calculated, they would be "cut off" at a certain character, and the remaining space filled with `A` characters, as the original report noted. Unfortunately this increases the chance of a collision when deduplicating records from each other and writing `revisit` WARC records, for which these digests are used.
